---
version: "2.1"
services:
  docker_bisq:
    image: maltokyo/docker-bisq:1.6.4
    # build: . #use this and comment out the above "image" line if you prefer to build yourself.
    container_name: docker_bisq
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      #- USER=myusername # not working yet - user is "abc" by default
      - PASSWORD=changeme #CHANGE THIS!!
      - S6_KILL_GRACETIME=10000 # This allows 10 seconds for Bisq to shutdown gracefully before the container will close.
      - CLI_ARGS="--userDataDir=/config/.config/BISQ/user_data --appDataDir=/config/.config/BISQ/app_data" #optional
    volumes:
      - ./config:/config
    ports:
      - 8080:8080
      #- 8081:8081
    restart: unless-stopped