---
version: "2.1"
services:
  docker_bisq:
    #image: maltokyo/docker-bisq
    build: .
    container_name: docker_bisq
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD="changeme" #optional
      - CLI_ARGS="--userDataDir=/config/.config/BISQ/user_data --appDataDir=/config/.config/BISQ/app_data" #optional
    volumes:
      - ./config:/config
    ports:
      - 8080:8080
      #- 8081:8081
    restart: unless-stopped